obj/Os/OSmain.o: ../Os/OSmain.c \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/stdio.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/_ansi.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/newlib.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/config.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/machine/ieeefp.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/include/stddef.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/include/stdarg.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/reent.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/_ansi.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/_types.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/types.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/machine/types.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/stdio.h \
  /cygdrive/d/altera/11.0/ip/altera/nios2_ip/altera_nios2/UCOSII/inc/includes.h \
  /cygdrive/d/altera/11.0/ip/altera/nios2_ip/altera_nios2/UCOSII/inc/os_cpu.h \
  /cygdrive/d/altera/11.0/ip/altera/nios2_ip/altera_nios2/HAL/inc/sys/alt_irq.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/errno.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/errno.h \
  /cygdrive/d/altera/11.0/ip/altera/nios2_ip/altera_nios2/HAL/inc/nios2.h \
  /cygdrive/d/altera/11.0/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /cygdrive/e/MyProject/My_project/Altera/Q11MultiCore/software/ucosCPU0_syslib/Debug/system_description/system.h \
  /cygdrive/d/altera/11.0/ip/altera/nios2_ip/altera_nios2/HAL/inc/priv/alt_legacy_irq.h \
  /cygdrive/e/MyProject/My_project/Altera/Q11MultiCore/software/ucosCPU0_syslib/Debug/system_description/system.h \
  /cygdrive/d/altera/11.0/ip/altera/nios2_ip/altera_nios2/HAL/inc/nios2.h \
  /cygdrive/d/altera/11.0/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /cygdrive/d/altera/11.0/ip/altera/nios2_ip/altera_nios2/HAL/inc/sys/alt_irq.h \
  /cygdrive/d/altera/11.0/nios2eds/components/micrium_uc_osii/UCOSII/inc/os_cfg.h \
  /cygdrive/d/altera/11.0/nios2eds/components/altera_hal/HAL/inc/sys/alt_alarm.h \
  /cygdrive/d/altera/11.0/nios2eds/components/altera_hal/HAL/inc/sys/alt_llist.h \
  /cygdrive/d/altera/11.0/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /cygdrive/d/altera/11.0/nios2eds/components/altera_hal/HAL/inc/priv/alt_alarm.h \
  /cygdrive/d/altera/11.0/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /cygdrive/e/MyProject/My_project/Altera/Q11MultiCore/software/ucosCPU0_syslib/Debug/system_description/system.h \
  /cygdrive/d/altera/11.0/nios2eds/components/micrium_uc_osii/UCOSII/inc/ucos_ii.h \
  /cygdrive/d/altera/11.0/nios2eds/components/micrium_uc_osii/UCOSII/inc/os_cfg.h \
  /cygdrive/d/altera/11.0/ip/altera/nios2_ip/altera_nios2/UCOSII/inc/os_cpu.h \
  ../Os/../inc/sopc.h \
  /cygdrive/e/MyProject/My_project/Altera/Q11MultiCore/software/ucosCPU0_syslib/Debug/system_description/system.h
