obj/altera_avalon_fifo_util.o:  \
 /cygdrive/d/altera/11.0/ip/altera/sopc_builder_ip/altera_avalon_fifo/HAL/src/altera_avalon_fifo_util.c \
  /cygdrive/d/altera/11.0/ip/altera/nios2_ip/altera_nios2/HAL/inc/io.h \
  /cygdrive/d/altera/11.0/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /cygdrive/d/altera/11.0/nios2eds/components/altera_hal/HAL/inc/sys/alt_errno.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/errno.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/errno.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/reent.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/_ansi.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/newlib.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/config.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/machine/ieeefp.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/_types.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/include/stddef.h \
  /cygdrive/d/altera/11.0/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /cygdrive/d/altera/11.0/nios2eds/components/altera_hal/HAL/inc/sys/alt_cache.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/stdlib.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/_ansi.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/machine/stdlib.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/alloca.h \
  /cygdrive/d/altera/11.0/ip/altera/sopc_builder_ip/altera_avalon_fifo/HAL/inc/altera_avalon_fifo.h \
  /cygdrive/d/altera/11.0/ip/altera/sopc_builder_ip/altera_avalon_fifo/HAL/inc/altera_avalon_fifo_util.h \
  /cygdrive/d/altera/11.0/ip/altera/sopc_builder_ip/altera_avalon_fifo/inc/altera_avalon_fifo_regs.h \
  /cygdrive/d/altera/11.0/ip/altera/nios2_ip/altera_nios2/HAL/inc/io.h
